# Generated by Django 6.0.7 on 2026-07-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For example: Managing Partner or Associate  or Intern.', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='attorneys/')),
                ('admission', models.CharField(blank=True, help_text='Court admission or professional designation.', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('practice_areas', models.ManyToManyField(blank=True, related_name='attorneys', to='practice_areas.practicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_order', 'user__last_name', 'user__first_name'),
            },
        ),
    ]
