# Generated by Django 6.0.7 on 2026-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='Khoboko Law Chambers', max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='site/branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/branding/')),
                ('primary_phone', models.CharField(blank=True, max_length=40)),
                ('secondary_phone', models.CharField(blank=True, max_length=40)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('business_hours', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.URLField(blank=True)),
                ('hero_title', models.CharField(default='Guiding you through the moments that matter.', max_length=255)),
                ('hero_text', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/hero/')),
                ('hero_cta_label', models.CharField(default='Request a consultation', max_length=80)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site information',
                'verbose_name_plural': 'site information',
            },
        ),
    ]
