# Generated by Django 6.0.7 on 2026-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='about_title',
            field=models.CharField(default='A firm grounded in service and integrity.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
    ]
